# Generated by Django 3.2.6 on 2021-09-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_vendas_clientes'),
        ('vendas', '0002_pedido'),
        ('manutencoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField()),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.funcionario')),
                ('terceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manutencoes.terceiro')),
            ],
        ),
    ]
