# Generated by Django 3.2.6 on 2021-11-17 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_pedido_status'),
        ('manutencoes', '0003_altera_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('C', 'Cancelado'), ('E', 'Em andamento'), ('F', 'Finalizado'), ('R', 'Recebido')], max_length=30, verbose_name='Status')),
                ('tipo', models.CharField(choices=[('C', 'Contato'), ('D', 'Devolução'), ('S', 'Suporte'), ('O', 'Outros')], max_length=30, verbose_name='Tipo de chamado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedido', verbose_name='Pedido')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.funcionario')),
            ],
        ),
    ]
