# Generated by Django 3.2.6 on 2021-11-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0004_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('E', 'Em andamento'), ('F', 'Finalizado'), ('R', 'Recebido')], max_length=30, verbose_name='Status'),
        ),
    ]
