# Generated by Django 3.2.6 on 2021-11-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_pedido_status'),
        ('manutencoes', '0004_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='mensagem',
            field=models.TextField(blank=True, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamado_pedido', to='vendas.pedido', verbose_name='Pedido'),
        ),
    ]
