# Generated by Django 3.2.6 on 2021-11-13 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0005_contato_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_fim',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 12, 55, 49, 989951)),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('E', 'Em andamento'), ('F', 'Finalizado'), ('R', 'Recebido')], max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipo',
            field=models.CharField(choices=[('C', 'Contato'), ('D', 'Devolução'), ('S', 'Suporte'), ('O', 'Outros')], max_length=30, verbose_name='Tipo de chamado'),
        ),
    ]
