# Generated by Django 3.2.6 on 2021-09-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
