# Generated by Django 3.2.6 on 2021-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_fornecedor_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
