# Generated by Django 3.2.6 on 2021-10-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_vendas_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
