# Generated by Django 3.2.6 on 2021-10-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
