# Generated by Django 3.2.6 on 2021-10-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
