# Generated by Django 3.2.6 on 2021-08-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/produtos'),
        ),
    ]
