# Generated by Django 3.2.6 on 2021-08-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_produtos', '0003_alter_produto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/produtos/%Y/%m/%d/'),
        ),
    ]
