# Generated by Django 3.2.6 on 2021-08-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_produtos', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/produtos'),
        ),
    ]
