# Generated by Django 3.2.6 on 2021-09-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_produtos', '0006_alter_produto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('ramo', models.CharField(max_length=50)),
                ('fornecedor_telefone', models.ManyToManyField(related_name='telefone_fornecedor', to='estoque_produtos.TelefoneFornecedor', verbose_name='Fornecedor Telefone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
