# Generated by Django 3.2.6 on 2021-08-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_produtos', '0007_auto_20210830_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefonefornecedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='telefonefornecedor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='telefonefornecedor',
            name='ramo',
        ),
        migrations.AddField(
            model_name='telefonefornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telefonefornecedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
