# Generated by Django 3.2.6 on 2021-09-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('email', models.CharField(max_length=80)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
