# Generated by Django 3.2.6 on 2021-09-21 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_vendas_clientes'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('rastreio', models.CharField(max_length=30)),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('E', 'Enviado'), ('R', 'Realizado'), ('F', 'Finalizado'), ('C', 'Cancelado')], max_length=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_cliente', to='vendas.clientes')),
                ('produtos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_produto', to='produtos.produto')),
            ],
        ),
    ]
