# Generated by Django 3.2.6 on 2021-10-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_cpf_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='percentual',
        ),
        migrations.CreateModel(
            name='ComissaoPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentual_comissao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=7)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.funcionario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedido')),
            ],
        ),
    ]
