# Generated by Django 3.2.6 on 2021-10-22 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_produto_custo'),
        ('vendas', '0004_comissao_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rastreio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='taxa_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='vendas.pedido')),
                ('produto', models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produto')),
            ],
        ),
    ]
