# Generated by Django 3.2.6 on 2021-10-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_funcionario_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('E', 'Enviado'), ('R', 'Realizado'), ('F', 'Finalizado')], max_length=10),
        ),
    ]
